export const actions = {
  ADD_TO_CART: 'ADD_TO_CART',
  SET_PRODUCTS: 'SET_PRODUCTS',
  STORE_OPERATING: 'STORE_OPERATING',
  ADD_TO_CART_OLD:'ADD_TO_CART_OLD',
  SET_PRODUCTS_OLD: 'SET_PRODUCTS_OLD',
}